command = ${HOMEBREW_PREFIX}/bin/fish --interactive --login

font-family = JetBrainsMonoNL NFM Regular
font-family-bold = JetBrainsMonoNL NFM Bold
font-family-italic = JetBrainsMonoNL NFM Italic
font-family-bold-italic = JetBrainsMonoNL NFM Bold Italic
font-size = "${font_size}"
adjust-cell-width = -10%

auto-update = off
background-opacity = 0.97
background-blur = true
copy-on-select =  false
cursor-click-to-move = true
cursor-style = block
cursor-style-blink = true
quick-terminal-animation-duration = 0
quick-terminal-autohide = true
quick-terminal-position = center
quick-terminal-space-behavior = remain
quit-after-last-window-closed = true
macos-titlebar-style = tabs
notify-on-command-finish = unfocused
scrollback-limit = 1048576
selection-clear-on-copy = false
selection-clear-on-typing = false
split-divider-color = #2d3f76
split-inherit-working-directory = true
shell-integration = detect
shell-integration-features = no-cursor
tab-inherit-working-directory = true
theme = TokyoNight Moon
unfocused-split-opacity = 0.60
window-decoration = true
window-height = ${terminal_window_height}
window-inherit-working-directory = false
window-padding-x = 6
window-padding-y = 6
window-save-state = always
window-width = ${terminal_window_width}

keybind = cmd+enter=new_tab
keybind = cmd+shift+enter=toggle_quick_terminal
keybind = cmd+h=goto_split:left
keybind = cmd+j=goto_split:bottom
keybind = cmd+k=goto_split:top
keybind = cmd+l=goto_split:right
keybind = cmd+i=previous_tab
keybind = cmd+o=next_tab
keybind = cmd+shift+i=move_tab:-1
keybind = cmd+shift+o=move_tab:+1
keybind = cmd+alt+h=new_split:left
keybind = cmd+alt+j=new_split:down
keybind = cmd+alt+k=new_split:up
keybind = cmd+alt+l=new_split:right
keybind = cmd+shift+h=resize_split:left,5
keybind = cmd+shift+j=resize_split:down,5
keybind = cmd+shift+k=resize_split:up,5
keybind = cmd+shift+l=resize_split:right,5
keybind = cmd+f=write_screen_file:paste
keybind = cmd+r=equalize_splits
keybind = cmd+z=toggle_split_zoom
